### ISSUE TITLE
No space left on device error

### ISSUE THREAD

**Issue by wsmoses** [StanfordSNR/gg#25]
occurs when running 

```
gg force --jobs 120 --engine lambda
```

```
invalid response: {"errorMessage": "[Errno 28] No space left on device", "errorType": "OSError", "stackTrace": [["/var/task/main.py", 43, "handler", "fout.write(thunk_data)"]]}
[warning] operational failure: T5iAFaPyLybWNOoRdpZPTdZCXoBcPG_WAd16s3CYR1iE0000188a
```

```
gg describe T5iAFaPyLybWNOoRdpZPTdZCXoBcPG_WAd16s3CYR1iE0000188a
```

```
{
 "function": {
  "hash": "VYA7BN_Oi7TEF.SFqo2yJu2fVpJOGPyeu5ThcID2g86400123508",
  "args": [
   "/__gg__/g++",
   "-specs=/__gg__/gcc-specs",
   "-DGTEST_HAS_RTTI=0",
   "-D_DEBUG",
   "-D_GNU_SOURCE",
   "-D__STDC_CONSTANT_MACROS",
   "-D__STDC_FORMAT_MACROS",
   "-D__STDC_LIMIT_MACROS",
   "-I/home/wmoses/git/Enzyme/build/lib/CodeGen/GlobalISel",
   "-I/home/wmoses/git/Enzyme/llvm/lib/CodeGen/GlobalISel",
   "-I/usr/include/libxml2",
   "-I/home/wmoses/git/Enzyme/build/include",
   "-I/home/wmoses/git/Enzyme/llvm/include",
   "-fPIC",
   "-fvisibility-inlines-hidden",
   "-Werror=date-time",
   "-std=c++11",
   "-Wall",
   "-Wextra",
   "-Wno-unused-parameter",
   "-Wwrite-strings",
   "-Wcast-qual",
   "-Wno-missing-field-initializers",
   "-pedantic",
   "-Wno-long-long",
   "-Wno-maybe-uninitialized",
   "-Wdelete-non-virtual-dtor",
   "-Wno-comment",
   "-fno-exceptions",
   "-fno-rtti",
   "-x",
   "assembler",
   "output_0_2",
   "-o",
   "CMakeFiles/LLVMGlobalISel.dir/Utils.cpp.o",
   "-c"
  ],
  "envars": [
   "PATH=/__gg__",
   "GG_MANIFEST=@{GGHASH:VmW1L9c5z_bGTeYCueoqAxuw5wS0pYezRqX1IvzndUv800000033}"
  ]
 },
 "values": [
  "VA6zg6HBuO14LpLZ1ypmPsViMlw6FyG_r8taoOFdhpxo000028bc=/__gg__/gcc-specs",
  "VhC0ciKSl6P6AnMPLfwsbcMBA6PNI6bfq4nwqVjHIXr000719d8f=output_0_2",
  "VmW1L9c5z_bGTeYCueoqAxuw5wS0pYezRqX1IvzndUv800000033"
 ],
 "thunks": [],
 "executables": [
  "VYA7BN_Oi7TEF.SFqo2yJu2fVpJOGPyeu5ThcID2g86400123508=/__gg__/g++",
  "VpHzj2kYtpl_SIMFqU9BiIKScB2vTXG6jkYOAaBGfRzE0020cb38=/__gg__/as"
 ],
 "outputs": [
  "output"
 ],
 "timeout": 7500
}
```

**Comment by ssnickolay** [comment]
The cause of the problem is described [here](https://stackoverflow.com/a/48347749).

I see that lambda function has garbage collection in [the beginning of the handler](https://github.com/StanfordSNR/gg/blob/master/src/remote/lambda_function/main.py#L35) but sometime it is not enough. I saw this error once when all executions of my function failed (there was an error on my side). A simple solution is to just wait for AWS to drop the execution context (~ 10 minutes).

**Comment by wsmoses** [comment]
Yeah, I noticed this went away after a while. I don't suppose there is a way we could get gg to flush/remove the context if it picks up this error?

**Comment by ssnickolay** [comment]
[AWS Lambda Execution Context](https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html) is something that lives inside AWS and does not have any external control capabilities. Moreover, a full description of the Execution Contex lifecycle is also unclear. We only know that it exists and is something like a cache, to support the "warmed up" lambda functions.
It may help to transfer the [tmp cleaning code](https://github.com/StanfordSNR/gg/blob/master/src/remote/lambda_function/main.py#L35) to the end of the function to avoid situation when the N-1 call "clogged up" memory. And only @sadjad can say whether it makes sense.

**Comment by sadjad** [comment]
>I see that lambda function has garbage collection in the beginning of the handler but sometime it is not enough.

You're totally right, but now I see that it is not enough. We put all the objects in `/tmp/_gg` directory and one solution would be getting rid of that altogether (we only write to this directory and `/tmp/thunk-execute.*`), but it's not the best decision, because it's possible that some of those blobs can be reused for the current thunk, and we would have to re-download them again.

I just pushed a change (533186475d406f8455bd667bd4f154d6730d8b63) that cleans out `/tmp/_gg`, only if the Lambda is out of space. It should fix this.

>AWS Lambda Execution Context is something that lives inside AWS and does not have any external control capabilities.

This is my understanding, too.

>It may help to transfer the tmp cleaning code to the end of the function to avoid situation when the N-1 call "clogged up" memory. 

`gg execute` cleans up the execution directories itself after the task is done; `main.py:35` is there to make sure we don't have any leftovers (e.g., in the case that the Lambda dies mid-job).
