### ISSUE TITLE
Build failure on Mac

### ISSUE THREAD

**Issue by anirudhSK** [StanfordSNR/gg#39]
When I try running docker-compose build, I get the following error at the end:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 287, in build
  File "compose/project.py", line 384, in build
  File "compose/project.py", line 366, in build_service
  File "compose/service.py", line 1082, in build
  File "site-packages/docker/api/build.py", line 251, in build
  File "site-packages/docker/api/build.py", line 313, in _set_auth_headers
  File "site-packages/docker/auth.py", line 96, in resolve_authconfig
  File "site-packages/docker/auth.py", line 146, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "".',)
[50589] Failed to execute script docker-compose

It also says this at the beginning:

ERROR: (gcloud.auth.docker-helper) There was a problem refreshing your current auth tokens: invalid_grant: Token has been expired or revoked.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.

This seems to be related to GCP. Is there a way to build gg for use just with AWS or do I need to have credentials for both GCP and AWS before I can install gg?

Thanks in advance for any help on this.

**Comment by sadjad** [comment]
Hi @anirudhSK -- great to see you here!

I think this is a problem with `docker-compose`, since `gg` doesn't do anything related to your AWS or Google Cloud account in the build process.

From the looks of it, for some reason, `docker-compose` seems to be trying to get the base images from an image repository in Google Cloud, and it tries to use the credentials stored on your system. Could you please run `docker-compose config` and post the output?

(Also, you may wanna take a look at https://github.com/docker/compose/issues/5930, if you haven't already).

Best,
Sadjad

**Comment by anirudhSK** [comment]
Here's the output from docker-compose config with some of the sensitive fields obfuscated.

networks:
  default: {}
services:
  gg:
    build:
      args:
        UBUNTU_VERSION: '18.04'
      context: /Users/anirudh/gg
      dockerfile: ./docker/Dockerfile
      target: sandbox-env
    environment:
      AWS_ACCESS_KEY_ID: ******************
      AWS_REGION: us-west-1
      AWS_SECRET_ACCESS_KEY: ************************
      GG_LAMBDA_ROLE: *********************
      GG_MODELPATH: /app/gg/src/models/wrappers
      GG_STORAGE_URI: ***************
      HISTFILE: /bundle/.bash_history
      PRY_HISTFILE: /bundle/.pry_history
    image: gg:0.0.1-development
    networks:
      default: null
    tmpfs:
    - /tmp
    volumes:
    - /Users/anirudh/gg:/app/gg:cached
    - /Users/anirudh/.ssh:/root/.ssh:ro
  runner:
    build:
      args:
        UBUNTU_VERSION: '18.04'
      context: /Users/anirudh/gg
      dockerfile: ./docker/Dockerfile
      target: sandbox-env
    entrypoint: /bin/bash
    environment:
      AWS_ACCESS_KEY_ID: ****************
      AWS_REGION: us-west-1
      AWS_SECRET_ACCESS_KEY: *********************
      GG_LAMBDA_ROLE: ********************
      GG_MODELPATH: /app/gg/src/models/wrappers
      GG_STORAGE_URI: **********************
      HISTFILE: /bundle/.bash_history
      PRY_HISTFILE: /bundle/.pry_history
    image: gg:0.0.1-development
    networks:
      default: null
    tmpfs:
    - /tmp
    volumes:
    - /Users/anirudh/gg:/app/gg:cached
    - /Users/anirudh/.ssh:/root/.ssh:ro
version: '3.4'
volumes:
  gg: {}

**Comment by sadjad** [comment]
I just double-checked and made sure that `gg` doesn't do anything with Google Cloud (or AWS) in the `build` step.

I think, for some reason, your `docker-compose` tries to download the base container images from Google Container Registry (gcr.io), and that's why you see that error. I guess you should look at your `$HOME/.docker/config.json` file, and see if you can see any mentions of `gcr.io` in there. Running `docker login` (with no other arguments) may help resetting this setting.

**Comment by anirudhSK** [comment]
Thanks! Deleting $HOME/.docker/config.json seems to fix this issue for now. Will let you know if I run into any more trouble.

**Comment by sadjad** [comment]
Awesome! Let me know if I can be of any help.
